//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_enrollattstudent
    {
        public int Student_id { get; set; }
        public string Student_title { get; set; }
        public string Student_name { get; set; }
        public string Student_lname { get; set; }
        public Nullable<int> att_id { get; set; }
        public Nullable<int> Staff_id { get; set; }
        public Nullable<int> qira_id { get; set; }
        public Nullable<int> page { get; set; }
        public Nullable<int> attday_id { get; set; }
    }
}
