//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int Class_id { get; set; }
        public Nullable<int> Status_class { get; set; }
        public string Class_name_id { get; set; }
        public Nullable<int> Teacher_id { get; set; }
        public Nullable<int> Class_room { get; set; }
        public Nullable<int> Class_year_index { get; set; }
    }
}
