//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestEducationSchool
    {
        public int TypeContest_id { get; set; }
        public string NameContest { get; set; }
        public Nullable<int> Staff_id { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> group { get; set; }
        public Nullable<System.DateTime> Day_contest { get; set; }
    }
}
