//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroll_EduContest
    {
        public int EduContest_id { get; set; }
        public Nullable<int> Type_id { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<System.DateTime> Timestamp__ { get; set; }
        public string result { get; set; }
    }
}
