//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollStudentCouse
    {
        public int EnrollStudentCouseId { get; set; }
        public Nullable<int> studentId { get; set; }
        public Nullable<int> EnrollCouseId { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<double> Grade { get; set; }
        public Nullable<int> TeacerId { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> YearEdu { get; set; }
        public Nullable<int> Staff { get; set; }
        public Nullable<int> Semester { get; set; }
    
        public virtual Enroll_Emp_Pos Enroll_Emp_Pos { get; set; }
        public virtual EnrollCouse EnrollCouse { get; set; }
        public virtual Students Students { get; set; }
    }
}
