//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroll_student_all_event
    {
        public int Student_id { get; set; }
        public int Class_id { get; set; }
        public int Enrol_stu_class_id { get; set; }
    }
}
