//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroll_paid
    {
        public int Paid_id { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<int> Monthly_id { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> Staff_paid_id { get; set; }
        public Nullable<int> Student_type_id { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<int> Class_id { get; set; }
        public Nullable<int> Pay_id { get; set; }
    }
}
