//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroll_pay
    {
        public int Pay_id { get; set; }
        public Nullable<int> Paid_id { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<int> Pay { get; set; }
        public Nullable<int> Staff_id { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Id_token { get; set; }
    }
}
