//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Family()
        {
            this.EnrollFamilyStudent = new HashSet<EnrollFamilyStudent>();
        }
    
        public int FamilyId { get; set; }
        public string Fam_Title { get; set; }
        public string Fam_Name { get; set; }
        public string Fam_Lname { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string Career { get; set; }
        public Nullable<int> Income { get; set; }
        public string Education { get; set; }
        public Nullable<System.DateTime> Timestam { get; set; }
        public Nullable<int> Staft { get; set; }
        public string Gender { get; set; }
        public string Idcard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollFamilyStudent> EnrollFamilyStudent { get; set; }
    }
}
