//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int Food_id { get; set; }
        public string Food_id_student { get; set; }
        public string Food_name { get; set; }
        public string Food_lastname { get; set; }
        public string Food_month_th { get; set; }
        public string Food_month_index { get; set; }
        public Nullable<int> Food_paid { get; set; }
        public Nullable<int> Food_full_paid { get; set; }
        public string Food_class { get; set; }
        public string Food_year { get; set; }
        public Nullable<System.DateTime> Food_timesatamp { get; set; }
        public string Food_update { get; set; }
        public Nullable<int> Food_paid_id { get; set; }
        public string Food_title { get; set; }
    }
}
