//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly
    {
        public int Monthly_id { get; set; }
        public string Month_name { get; set; }
        public Nullable<int> Month_year { get; set; }
        public Nullable<int> Month_course { get; set; }
        public Nullable<bool> Month_status { get; set; }
        public Nullable<int> Month_yearindex { get; set; }
    }
}
