//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentEduContest2561
    {
        public int EduContest_id { get; set; }
        public int Student_id { get; set; }
        public string Student_title { get; set; }
        public string Student_name { get; set; }
        public string Student_lname { get; set; }
        public string Class_name_id { get; set; }
        public Nullable<int> Class_room { get; set; }
        public Nullable<int> Class_year_index { get; set; }
        public Nullable<int> Teacher_id { get; set; }
        public int Class_id { get; set; }
        public int TypeContest_id { get; set; }
        public string NameContest { get; set; }
        public Nullable<int> Staff_id { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> group { get; set; }
        public Nullable<System.DateTime> Day_contest { get; set; }
        public string result { get; set; }
    }
}
