//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student2561_copy1
    {
        public int Student_id { get; set; }
        public string Student_title { get; set; }
        public string Student_name { get; set; }
        public string Student_lname { get; set; }
        public Nullable<System.DateTime> Student_birthday { get; set; }
        public string Student_idcard { get; set; }
        public Nullable<int> Student_psis_id { get; set; }
        public string Student_status { get; set; }
        public Nullable<System.DateTime> Student_timestamp { get; set; }
        public string Class_name_id { get; set; }
        public Nullable<int> Class_room { get; set; }
        public Nullable<int> Class_year_index { get; set; }
        public Nullable<int> Teacher_id { get; set; }
        public int Class_id { get; set; }
    }
}
