//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmpPos
    {
        public string EmpTitle { get; set; }
        public string EmpName { get; set; }
        public string EmpLname { get; set; }
        public Nullable<System.DateTime> EmpBirthday { get; set; }
        public Nullable<int> EmpIdcard { get; set; }
        public Nullable<int> EmpPsis_id { get; set; }
        public Nullable<int> EmpStatus { get; set; }
        public Nullable<System.DateTime> EmpTimestamp { get; set; }
        public string EmpTelephone { get; set; }
        public string Empbank_id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> EmpGender { get; set; }
        public int EnrEmpPosId { get; set; }
        public Nullable<int> EnrEmpPosStatus { get; set; }
        public Nullable<System.DateTime> EnrEmpPosTimestamp { get; set; }
        public string PosName { get; set; }
        public Nullable<int> PosLevel { get; set; }
        public Nullable<int> PosId { get; set; }
    }
}
