//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Couse
    {
        public string CouseTxtId { get; set; }
        public Nullable<int> DepartId { get; set; }
        public Nullable<int> CouseTime { get; set; }
        public Nullable<float> CouseWeight__ { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> semester__ { get; set; }
        public int EnrollCouseID { get; set; }
        public string CouseExcel { get; set; }
        public Nullable<int> CouseId { get; set; }
        public string CourseName { get; set; }
        public string CourseType { get; set; }
        public Nullable<int> CourseStatus { get; set; }
        public int EnrollStudentCouseId { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<double> Grade { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> YearEdu { get; set; }
        public Nullable<int> Staff { get; set; }
        public Nullable<int> Semester { get; set; }
        public string Student_title { get; set; }
        public string Student_name { get; set; }
        public string Student_lname { get; set; }
        public Nullable<System.DateTime> Student_birthday { get; set; }
        public string Student_idcard { get; set; }
        public Nullable<int> Student_psis_id { get; set; }
        public string Student_status { get; set; }
        public Nullable<System.DateTime> Student_timestamp { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public Nullable<int> Position_id { get; set; }
        public Nullable<int> EnrEmpPosStatus { get; set; }
        public Nullable<System.DateTime> EnrEmpPosTimestamp { get; set; }
        public int EnrEmpPosId { get; set; }
        public string EmpTitle { get; set; }
        public string EmpName { get; set; }
        public string EmpLname { get; set; }
        public Nullable<System.DateTime> EmpBirthday { get; set; }
        public Nullable<int> EmpIdcard { get; set; }
        public Nullable<int> EmpPsis_id { get; set; }
        public Nullable<int> EmpStatus { get; set; }
        public Nullable<System.DateTime> EmpTimestamp { get; set; }
        public string EmpTelephone { get; set; }
        public string Empbank_id { get; set; }
        public int EmpId { get; set; }
        public Nullable<int> EmpGender { get; set; }
        public int Student_id { get; set; }
        public int CourseId { get; set; }
    }
}
