//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollEmpCouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnrollEmpCouse()
        {
            this.EnrollCouse1 = new HashSet<EnrollCouse>();
        }
    
        public Nullable<int> EnCouseId { get; set; }
        public Nullable<System.DateTime> EnEmpCosTimestamp { get; set; }
        public int EnrollEmpCouseId { get; set; }
        public Nullable<int> EnEmpId { get; set; }
        public Nullable<int> EnYearSemId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EnrollCouse EnrollCouse { get; set; }
        public virtual EnrollYearSemester EnrollYearSemester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollCouse> EnrollCouse1 { get; set; }
    }
}
