//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnrollClass()
        {
            this.Enroll_student_class = new HashSet<Enroll_student_class>();
        }
    
        public Nullable<int> Status_class { get; set; }
        public Nullable<int> ClassSchoolid { get; set; }
        public Nullable<int> Teacher_id { get; set; }
        public Nullable<int> Class_room { get; set; }
        public Nullable<int> Class_year_index { get; set; }
        public int EnrollClass_id { get; set; }
    
        public virtual ClassInSchool ClassInSchool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enroll_student_class> Enroll_student_class { get; set; }
    }
}
