//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroll_reportTruckKpi
    {
        public int id_report { get; set; }
        public Nullable<double> kpi { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> meter_last { get; set; }
        public Nullable<double> petrol_last { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> car_id { get; set; }
    
        public virtual truck truck { get; set; }
    }
}
