//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroll_truck
    {
        public Nullable<int> car_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public int id { get; set; }
    }
}
