//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomSession()
        {
            this.Enroll_RoomSession_Emp = new HashSet<Enroll_RoomSession_Emp>();
        }
    
        public string RoomName { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> Status { get; set; }
        public int RoomSessionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enroll_RoomSession_Emp> Enroll_RoomSession_Emp { get; set; }
    }
}
