//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class backupServerEntities1 : DbContext
    {
        public backupServerEntities1()
            : base("name=backupServerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<attendance_day> attendance_day { get; set; }
        public virtual DbSet<C_enrollattstudent> C_enrollattstudent { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassInSchool> ClassInSchools { get; set; }
        public virtual DbSet<ContestEducationSchool> ContestEducationSchools { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Enroll_EduContest> Enroll_EduContest { get; set; }
        public virtual DbSet<Enroll_Emp_Pos> Enroll_Emp_Pos { get; set; }
        public virtual DbSet<Enroll_paid> Enroll_paid { get; set; }
        public virtual DbSet<Enroll_pay> Enroll_pay { get; set; }
        public virtual DbSet<Enroll_RoomSession_Emp> Enroll_RoomSession_Emp { get; set; }
        public virtual DbSet<Enroll_student_all_event> Enroll_student_all_event { get; set; }
        public virtual DbSet<Enroll_student_class> Enroll_student_class { get; set; }
        public virtual DbSet<EnrollClass> EnrollClasses { get; set; }
        public virtual DbSet<EnrollCouse> EnrollCouses { get; set; }
        public virtual DbSet<EnrollEmpCouse> EnrollEmpCouses { get; set; }
        public virtual DbSet<EnrollEmpCouseClass> EnrollEmpCouseClasses { get; set; }
        public virtual DbSet<EnrollFamilyStudent> EnrollFamilyStudents { get; set; }
        public virtual DbSet<EnrollFinishStudent> EnrollFinishStudents { get; set; }
        public virtual DbSet<EnrollStudentAttdance> EnrollStudentAttdances { get; set; }
        public virtual DbSet<EnrollStudentCouse> EnrollStudentCouses { get; set; }
        public virtual DbSet<EnrollYearSemester> EnrollYearSemesters { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<FinishType> FinishTypes { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Monthly> Monthlies { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<RoomSession> RoomSessions { get; set; }
        public virtual DbSet<student2561> student2561 { get; set; }
        public virtual DbSet<student2561_copy1> student2561_copy1 { get; set; }
        public virtual DbSet<student2561_food> student2561_food { get; set; }
        public virtual DbSet<studentEduContest2561> studentEduContest2561 { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Students_food> Students_food { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<View_Couse> View_Couse { get; set; }
        public virtual DbSet<ViewEmpPos> ViewEmpPos { get; set; }
        public virtual DbSet<YearEdu> YearEdus { get; set; }
        public virtual DbSet<Employee_copy1> Employee_copy1 { get; set; }
        public virtual DbSet<Enroll_Emp_Pos_copy1> Enroll_Emp_Pos_copy1 { get; set; }
        public virtual DbSet<TestCourse> TestCourses { get; set; }
        public virtual DbSet<TestCourseInstructor> TestCourseInstructors { get; set; }
        public virtual DbSet<TestDepartment> TestDepartments { get; set; }
        public virtual DbSet<TestInstructor> TestInstructors { get; set; }
        public virtual DbSet<TestStudent> TestStudents { get; set; }
        public virtual DbSet<TestStudentCourse> TestStudentCourses { get; set; }
        public virtual DbSet<C_enrollattstudent1> C_enrollattstudent1 { get; set; }
        public virtual DbSet<EnrollStudentAttdance1> EnrollStudentAttdance1 { get; set; }
        public virtual DbSet<student25611> student25611 { get; set; }
        public virtual DbSet<student2561_copy11> student2561_copy11 { get; set; }
        public virtual DbSet<student2561_food1> student2561_food1 { get; set; }
        public virtual DbSet<studentEduContest25611> studentEduContest25611 { get; set; }
        public virtual DbSet<ViewEmpPos1> ViewEmpPos1 { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
    }
}
