//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisart_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class truck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public truck()
        {
            this.Enroll_reportTruckKpi = new HashSet<Enroll_reportTruckKpi>();
            this.payPetrols = new HashSet<payPetrol>();
        }
    
        public string id_truck { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string type { get; set; }
        public int car_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> excelPageReportKpi { get; set; }
    
        public virtual company company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enroll_reportTruckKpi> Enroll_reportTruckKpi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payPetrol> payPetrols { get; set; }
    }
}
